
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "12.0"
branches:
  only:
    - master
before_install:
  - cd AdministrationWebApp
before_script:
  - npm install --save-dev @angular-devkit/build-angular
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - npm install
  - ng lint
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
