sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "12.0"
branches:
  only:
    - master
    - task/inmemory-db
before_install:
  - cd AdministrationWebApp
before_script:
  - npm install --save-dev @angular-devkit/build-angular
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - npm install
  - ng lint
  - ng build --prod --aot
after_success:
  - firebase use default
  - firebase deploy --token 1/gZZjbfzz7vjcb8vgm8pUqz1nOXeDasBcT_NsxDsnQBU
